### ISSUE TITLE
Feature request: possible to add an option to make overlay the default option?

### ISSUE THREAD

**Issue by rc-glean** [tiagofilipenunes/git-image-diff#2]
<img width="950" alt="Screenshot 2024-09-12 at 11 48 14 AM" src="https://github.com/user-attachments/assets/5f3dbe43-288f-4739-a4ea-c8c4a9ff8ad1">

Or if you don't have don't have the bandwidth, are you willing to accept patches @tiagofilipenunes?

My first naive thought is to to use chrome.storage to maintain options like this defunct extension https://github.com/bentleyvk/github-pr-image-comparer/blob/bfad2ad8d07101163648df5480e97ac332ffb399/src/content.js#L18-L23, 

https://chromewebstore.google.com/detail/github-pr-images-comparer/fdbkbdjkkjlceenjnkdopiiibkhlknlm?hl=en

Which used to work well before a github redesign

**Comment by tiagofilipenunes** [comment]
Hey @rc-glean thanks for the suggestion! I'm working on a refactor to allow the extension to be used with Firefox and will work on improving the options popup next. I'll add an option to set the default option as part of it. 

Feel free to send any other suggestions :)

**Comment by tiagofilipenunes** [comment]
Hey @rc-glean I added some default action functionality. It's currently not ideal but can be improved it over time (#7)

**Comment by rc-glean** [comment]
Thank you so much @tiagofilipenunes. You and your project are amazing 😄.

We at Glean are surprised that GitHub doesn't have a native heatmap diff feature. And your extension makes it much easier to review storybook screen shot changes which we use heavily. Prior to your extension, we've had visual bugs slide through because we could have 15+ image diffs, and it's tedious to github UI-swipe all of them  to diff
